// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    // Test name: test1
    // Step # | name | target | value
    // 1 | click | name=query | 
    driver.findElement(By.name("query")).click();
    // 2 | click | css=.b-main-navigation__item:nth-child(3) .b-main-navigation__text | 
    driver.findElement(By.cssSelector(".b-main-navigation__item:nth-child(3) .b-main-navigation__text")).click();
    // 3 | click | css=.b-main-navigation__item:nth-child(7) .b-main-navigation__text | 
    driver.findElement(By.cssSelector(".b-main-navigation__item:nth-child(7) .b-main-navigation__text")).click();
    // 4 | click | css=.catalog-form__row:nth-child(9) .catalog-form__checkbox-item:nth-child(4) | 
    driver.findElement(By.cssSelector(".catalog-form__row:nth-child(9) .catalog-form__checkbox-item:nth-child(4)")).click();
    // 5 | click | css=.catalog-form__group:nth-child(1) .input-style__combo > .input-style__wrapper:nth-child(1) > .input-style | 
    driver.findElement(By.cssSelector(".catalog-form__group:nth-child(1) .input-style__combo > .input-style__wrapper:nth-child(1) > .input-style")).click();
    // 6 | type | css=.catalog-form__group:nth-child(1) .input-style__combo > .input-style__wrapper:nth-child(1) > .input-style | 600
    driver.findElement(By.cssSelector(".catalog-form__group:nth-child(1) .input-style__combo > .input-style__wrapper:nth-child(1) > .input-style")).sendKeys("600");
    // 7 | click | css=.catalog-form__row:nth-child(13) .catalog-form__checkbox-item:nth-child(3) | 
    driver.findElement(By.cssSelector(".catalog-form__row:nth-child(13) .catalog-form__checkbox-item:nth-child(3)")).click();
    // 8 | click | css=.catalog-form__row:nth-child(15) .catalog-form__checkbox-item:nth-child(1) | 
    driver.findElement(By.cssSelector(".catalog-form__row:nth-child(15) .catalog-form__checkbox-item:nth-child(1)")).click();
    // 9 | click | css=.catalog-form__checkbox-item_active:nth-child(4) | 
    driver.findElement(By.cssSelector(".catalog-form__checkbox-item_active:nth-child(4)")).click();
    // 10 | click | css=.catalog-form__row:nth-child(36) .input-style__wrapper:nth-child(1) > .input-style | 
    driver.findElement(By.cssSelector(".catalog-form__row:nth-child(36) .input-style__wrapper:nth-child(1) > .input-style")).click();
    // 11 | click | linkText=Поддержка пользователей | 
    driver.findElement(By.linkText("Поддержка пользователей")).click();
    // 12 | click | css=.button-style_complementary | 
    driver.findElement(By.cssSelector(".button-style_complementary")).click();
    // 13 | click | css=.catalog-form__offers-unit:nth-child(1) .catalog-form__image | 
    driver.findElement(By.cssSelector(".catalog-form__offers-unit:nth-child(1) .catalog-form__image")).click();
    // 14 | click | css=.catalog-form__offers-unit:nth-child(7) .catalog-form__image | 
    driver.findElement(By.cssSelector(".catalog-form__offers-unit:nth-child(7) .catalog-form__image")).click();
    // 15 | click | css=.catalog-form__offers-unit:nth-child(14) .catalog-form__image | 
    driver.findElement(By.cssSelector(".catalog-form__offers-unit:nth-child(14) .catalog-form__image")).click();
  }
}
